// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbrzt7NugglF_H1OqP45Y1YArsT4yHP2c',
    appId: '1:694595341378:web:022adcd01483c09c88f1db',
    messagingSenderId: '694595341378',
    projectId: 'hackdavis24-59799',
    authDomain: 'hackdavis24-59799.firebaseapp.com',
    storageBucket: 'hackdavis24-59799.appspot.com',
    measurementId: 'G-62DQC040GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGWNTxCcfWRJlCJ5DcXumOkIDlq3BoRHs',
    appId: '1:694595341378:android:eb78827fc53db29c88f1db',
    messagingSenderId: '694595341378',
    projectId: 'hackdavis24-59799',
    storageBucket: 'hackdavis24-59799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGLpezY2KASuDfGVKJ8nTT7a4R-ZNHhpQ',
    appId: '1:694595341378:ios:1527d8d33875168a88f1db',
    messagingSenderId: '694595341378',
    projectId: 'hackdavis24-59799',
    storageBucket: 'hackdavis24-59799.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGLpezY2KASuDfGVKJ8nTT7a4R-ZNHhpQ',
    appId: '1:694595341378:ios:1527d8d33875168a88f1db',
    messagingSenderId: '694595341378',
    projectId: 'hackdavis24-59799',
    storageBucket: 'hackdavis24-59799.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbrzt7NugglF_H1OqP45Y1YArsT4yHP2c',
    appId: '1:694595341378:web:328278834867c5f288f1db',
    messagingSenderId: '694595341378',
    projectId: 'hackdavis24-59799',
    authDomain: 'hackdavis24-59799.firebaseapp.com',
    storageBucket: 'hackdavis24-59799.appspot.com',
    measurementId: 'G-GDMQEQJSGV',
  );

}